<?php

namespace App\Imports;

use App\Models\Plano_cartera;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class PlanoCarteraImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
        return new Plano_cartera([
            'suc_cliente' => $row['suc_cliente'] ?? null,
            'id_cliente' => $row['id_cliente'] ?? null,
            'nombre' => $row['nombre'] ?? null,
            'estado' => $row['estado'] ?? null,
            'medio_de_pago' => $row['medio_de_pago'] ?? null,
            'sld_aportes' => $row['sld_aportes'] ?? null,
            'tipo_obl' => $row['tipo_obl'] ?? null,
            'no_obligacion' => $row['no_obligacion'] ?? null,
            'monto_solicitado' => $row['monto_solicitado'] ?? null,
            'saldo_capital' => $row['saldo_capital'] ?? null,
            'sld_int' => $row['sld_int'] ?? null,
            'sld_mora' => $row['sld_mora'] ?? null,
            'dias_vencidos' => $row['dias_vencidos'] ?? null,
            'venc_capital' => $row['venc_capital'] ?? null,
            'tasa_col_namv' => $row['tasa_col_namv'] ?? null,
            'tasa_peridodo_namv' => $row['tasa_peridodo_namv'] ?? null,
            'clasificacion' => $row['clasificacion'] ?? null,
            'linea_de_credito' => $row['linea_de_credito'] ?? null,
            'destinacion' => $row['destinacion'] ?? null,
            'modalidad' => $row['modalidad'] ?? null,
            'medio_de_pago_obligacion' => $row['medio_de_pago_obligacion'] ?? null,
            'tipo_garantia' => $row['tipo_garantia'] ?? null,
            'vlr_garantia' => $row['vlr_garantia'] ?? null,
            'vlr_cobertura_disponible' => $row['vlr_cobertura_disponible'] ?? null,
            'vlr_prov_capital' => $row['vlr_prov_capital'] ?? null,
            'vlr_prov_interes' => $row['vlr_prov_interes'] ?? null,
            'vlr_aportes_util_en_la_provision' => $row['vlr_aportes_util_en_la_provision'] ?? null,
            'fec_aprobacion' => $row['fec_aprobacion'] ?? null,
            'fec_prestamo' => $row['fec_prestamo'] ?? null,
            'fec_liquidacion' => $row['fec_liquidacion'] ?? null,
            'vlr_cuota' => $row['vlr_cuota'] ?? null,
            'no_cuotas' => $row['no_cuotas'] ?? null,
            'periodicidad' => $row['periodicidad'] ?? null,
            'fec_inicio' => $row['fec_inicio'] ?? null,
            'fec_vcto_final' => $row['fec_vcto_final'] ?? null,
            'altura' => $row['altura'] ?? null,
            'fec_vencto' => $row['fec_vencto'] ?? null,
            'calif_antes_ley_arrast' => $row['calif_antes_ley_arrast'] ?? null,
            'calif_aplicada' => $row['calif_aplicada'] ?? null,
            'calif_mes_ant' => $row['calif_mes_ant'] ?? null,
            'int_cte_orden' => $row['int_cte_orden'] ?? null,
            'int_mora_orden' => $row['int_mora_orden'] ?? null,
            'fec_historico' => $row['fec_historico'] ?? null,
            'sld_seg_vida' => $row['sld_seg_vida'] ?? null,
            'sld_seg_patrimonial' => $row['sld_seg_patrimonial'] ?? null,
            'forma_de_pago' => $row['forma_de_pago'] ?? null,
            'fec_ult_pago' => $row['fec_ult_pago'] ?? null,
            'cuenta_contable' => $row['cuenta_contable'] ?? null,
            'suc_credito' => $row['suc_credito'] ?? null,
            'cod_garantia' => $row['cod_garantia'] ?? null,
            'cantidad_garantias' => $row['cantidad_garantias'] ?? null,
            'porc_cobertura_garant' => $row['porc_cobertura_garant'] ?? null,
            'vlr_aplicado_garant' => $row['vlr_aplicado_garant'] ?? null,
            'codeudores' => $row['codeudores'] ?? null,
            'garantia_real' => $row['garantia_real'] ?? null,
            'pagare' => $row['pagare'] ?? null,
            'c_costo_cli' => $row['c_costo_cli'] ?? null,
            'c_costo_obl' => $row['c_costo_obl'] ?? null,
            'dias_vencidos_int' => $row['dias_vencidos_int'] ?? null,
            'instan_aprob' => $row['instan_aprob'] ?? null,
            'vencido_int' => $row['vencido_int'] ?? null,
            'dias_vencidos_capital' => $row['dias_vencidos_capital'] ?? null,
            'prob_incumplimiento_sistema' => $row['prob_incumplimiento_sistema'] ?? null,
            'prob_incumplimiento_manual' => $row['prob_incumplimiento_manual'] ?? null,
            'perdida_incumplimiento_sistema' => $row['perdida_incumplimiento_sistema'] ?? null,
            'perdida_incumplimiento_manual' => $row['perdida_incumplimiento_manual'] ?? null,
            'valor_expuesto' => $row['valor_expuesto'] ?? null,
            'valor_perdida_esperada_aplicada' => $row['valor_perdida_esperada_aplicada'] ?? null,
            'valor_comercial_activos' => $row['valor_comercial_activos'] ?? null,
            'valor_saldo_pasivos' => $row['valor_saldo_pasivos'] ?? null,
            'scoring' => $row['scoring'] ?? null,
            'fecha_restructuracion' => $row['fecha_restructuracion'] ?? null,
            'valor_garantia' => $row['valor_garantia'] ?? null,
        ]);
    }
}
