<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AuditoriaCartera extends Model
{
    protected $fillable = [
        'id_cliente',
        'sld_aportes',
        'tipo_obl',
        'no_obligacion',
        'saldo_capital',
        'sld_int',
        'sld_mora',
        'dias_vencidos',
        'venc_capital',
        'tasa_col_namv',
        'tasa_peridodo_namv',
        'vlr_garantia',
        'vlr_cobertura_disponible',
        'vlr_prov_capital',
        'vlr_prov_interes',
        'vlr_aportes_util_en_la_provision',
        'vlr_cuota',
        'no_cuotas',
        'fec_vcto_final',
        'altura',
        'fec_vencto',
        'calif_antes_ley_arrast',
        'calif_aplicada',
        'calif_mes_ant',
        'int_cte_orden',
        'int_mora_orden',
        'fec_historico',
        'sld_seg_vida',
        'sld_seg_patrimonial',
        'fec_ult_pago',
        'cuenta_contable',
        'cod_garantia',
        'cantidad_garantias',
        'porc_cobertura_garant',
        'vlr_aplicado_garant',
        'pagare',
        'c_costo_cli',
        'c_costo_obl',
        'dias_vencidos_int',
        'instan_aprob',
        'vencido_int',
        'dias_vencidos_capital',
        'perdida_incumplimiento_sistema',
        'perdida_incumplimiento_manual',
        'valor_expuesto',
        'valor_perdida_esperada_aplicada',
        'valor_comercial_activos',
        'valor_saldo_pasivos',
        'scoring',
        'fecha_restructuracion',
        'valor_garantia',
        'fecha_modificacion',
        'user_id',
    ];
}
