<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Plano_cartera extends Model
{
    protected $table = 'plano_cartera';

    protected $fillable = [
        'suc_cliente',
        'id_cliente',
        'nombre',
        'estado',
        'medio_de_pago',
        'sld_aportes',
        'tipo_obl',
        'no_obligacion',
        'monto_solicitado',
        'saldo_capital',
        'sld_int',
        'sld_mora',
        'dias_vencidos',
        'venc_capital',
        'tasa_col_namv',
        'tasa_peridodo_namv',
        'clasificacion',
        'linea_de_credito',
        'destinacion',
        'modalidad',
        'medio_de_pago_obligacion',
        'tipo_garantia',
        'vlr_garantia',
        'vlr_cobertura_disponible',
        'vlr_prov_capital',
        'vlr_prov_interes',
        'vlr_aportes_util_en_la_provision',
        'fec_aprobacion',
        'fec_prestamo',
        'fec_liquidacion',
        'vlr_cuota',
        'no_cuotas',
        'periodicidad',
        'fec_inicio',
        'fec_vcto_final',
        'altura',
        'fec_vencto',
        'calif_antes_ley_arrast',
        'calif_aplicada',
        'calif_mes_ant',
        'int_cte_orden',
        'int_mora_orden',
        'fec_historico',
        'sld_seg_vida',
        'sld_seg_patrimonial',
        'forma_de_pago',
        'fec_ult_pago',
        'cuenta_contable',
        'suc_credito',
        'cod_garantia',
        'cantidad_garantias',
        'porc_cobertura_garant',
        'vlr_aplicado_garant',
        'codeudores',
        'garantia_real',
        'pagare',
        'c_costo_cli',
        'c_costo_obl',
        'dias_vencidos_int',
        'instan_aprob',
        'vencido_int',
        'dias_vencidos_capital',
        'prob_incumplimiento_sistema',
        'prob_incumplimiento_manual',
        'perdida_incumplimiento_sistema',
        'perdida_incumplimiento_manual',
        'valor_expuesto',
        'valor_perdida_esperada_aplicada',
        'valor_comercial_activos',
        'valor_saldo_pasivos',
        'scoring',
        'fecha_restructuracion',
        'valor_garantia',
    ];
}
